CREATE TABLE environmental_data (
    timestamp TIMESTAMP PRIMARY KEY DEFAULT CURRENT_TIMESTAMP,
    temp DOUBLE PRECISION NOT NULL,
    humid DOUBLE PRECISION NOT NULL,
    perceived_temp DOUBLE PRECISION
);