services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5435:5432
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres_data:/var/lib/postgresql/data

  sensor-poller:
    build:
      context: .
      dockerfile: sensor-poller.Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: data
      DB_USER: postgres
      DB_PASS: postgres
      SENSOR_URL: http://sensor.local/get
      INTERVAL: 60  # 1 minute

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "5173:3000"
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
