services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5435:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  sensor-poller:
    build:
      context: ./sensor-poller
      dockerfile: sensor-poller.Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    dns:
      - 192.168.1.1  # replace with your router’s IP

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    dns:
      - 192.168.1.1 

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "5173:3000"
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
