services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5435:5432
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres_data:/var/lib/postgresql/data

  sensor-poller:
    build:
      context: .
      dockerfile: sensor-poller.Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    dns:
      - 192.168.1.1  # replace with your router’s IP

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    dns:
      - 192.168.1.1 

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "5173:3000"
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
